testcontainers/testcontainers-python

setup.py, testcontainers/mysql.py, tests/test_db_containers.py
I've got 2 test cases with MySQL:
1) Testing under the user "root"
2) Testing without specifying a database (our application creates DB by himself)
Now it's possible to use MySQL container in both of 2 these cases
=> MySQL container configuration

testcontainers/__init__.py
Fix for https://github.com/SergeyPirogov/testcontainers-python/issues/13
=> Remove container specific import from __init__.py

Dockerfile, Pipfile.lock, testcontainers/core/container.py, testcontainers/core/docker_client.py, testcontainers/core/utils.py
This commit adds support for running `testcontainers` inside Docker using the so-called "docker-outside-of-docker" approach: by mounting `/var/run/docker.sock` into the Docker container (using, for example, `docker run -v /var/run/docker.sock:/var/run/docker.sock ...`), one can spawn the test containers as sibling-containers.
To determine whether `testcontainers` is run inside a container, it checks whether a `/.dockerenv` file exists.
This PR also adds a simple `Dockerfile` that one can use to for testing. I have not, however, updated the `.travis.yml` to test this in CI - I'm open for suggestions on how to do so.
It also includes a small fix I made to make sure that Docker containers are stopped even when an exception is thrown:
```python
def __del__(self):
"""
Try to remove the …
```
=> Add support for docker-outside-of-docker

testcontainers/elasticsearch.py, testcontainers/general.py, testcontainers/redis.py
Add an implementation of the elasticsearch container.
=> Add elasticsearch container

.travis.yml, README.md, setup.py
This PR 
* adds functionality to deploy to pypi when the master branch is built.
* bumps the minor version number.
* fixes some links in the README.
@SergeyPirogov, as I'm not a maintainer on pypi, I can't add my own encrypted password to deploy. Two options: (a) you can add me as a maintainer and I can deploy using my account, or (b) you can follow the instructions [here](https://docs.travis-ci.com/user/deployment/pypi/) to encrypt your password and add the password in the `.travis.yml` file.
This should also resolve #27.
=> Deploy to pypi on merge into master

testcontainers/compose.py
I think it would be a nice addition to be really clean and remove all volumes that may have been created in the docker-compose. This does that.
=> Add -v to docker-compose down to remove created volumes again

testcontainers/core/container.py, tests/test_new_docker_api.py
Allow passing in any parameters supported by docker, so that user can pass in 
- New parameters supported by docker 
- Existing parameters but not supported by testcontainers, e.g. there are almost hundred parameters at: https://docker-py.readthedocs.io/en/stable/containers.html
In my own scenario, I need to start a container which shares the same volume from another container (not created by testcontainer).
=> Allow passing in any parameters supported by docker

testcontainers/compose.py
#29 
Allows user to specify the docker-compose file used by passing the parameter `compose_file_name`. Defaults to `docker-compose.yml` which maintains backwards compatibility.
=> #29 specify docker-compose file

Pipfile, Pipfile.lock, setup.py
Quoting [the `psycopg2-binary` web page](https://pypi.org/project/psycopg2-binary/):
> The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources.
For me right now, not having had to build `psycopg2` from source while testing would have made my life easier.
=> Use binary psycopg2 packages

docs/database.rst, docs/index.rst, testcontainers/elasticsearch.py, tests/test_elasticsearch.py
* elasticsearch:latest no longer exists
* Entrypoint has changed too; pass stuff as environment variables instead
* Refactor method to calculate URL
* Add some testing
* Add some docs, reference in index.rst
=> Update Elasticsearch support

testcontainers/core/waiting_utils.py, tests/test_core.py, tests/test_google.py
Reduce test time by waiting for specific log message rather than suspending execution. Cf #52.
=> Add option to wait for logs.

docs/compose.rst, testcontainers/compose.py, tests/test_docker_compose.py
This PR adds `pull` option to `DockerCompose`. 
See #72 for details.
=> Allow to pull images before compose start

testcontainers/core/container.py
There is an older PR for this change but it is outdated.
=> Fix typo: get_wrapped_contaner -> get_wrapped_container

testcontainers/compose.py
Otherwise, the wrong `docker-compose.yml` is used.
This was omitted in 7bf56870964d077a082d6c5950d2010072a739d0
=> Use compose_file_name in _get_service_info

testcontainers/core/container.py
Fix:
- Stuck when running inside docker container with docker socket is mounted. Reported by @karmux [here](https://github.com/testcontainers/testcontainers-python/issues/43#issuecomment-635504867) in issue #43
=> Fallback to gateway address if it is running inside a container

testcontainers/compose.py, tests/test_docker_compose.py
This PR adds ability to get logs from containers started by `DockerCompose`. See https://github.com/testcontainers/testcontainers-python/issues/92
=> Allow to get logs from compose

testcontainers/compose.py, testcontainers/core/container.py, tests/docker-compose-2.yml, tests/test_docker_compose.py
With this patch, users are able to separate some common used services into a reusable `docker-compose.yml` and specify multiple `docker-compose.yml`s in the `DockerCompose` class, like 
```python
DockerCompose(filepath=os.path.join(docker_dir, 'http'), compose_file_name=[
'skywalking-python-sdk/tests/plugin/docker/base-compose.yml',
'skywalking-python-sdk/tests/plugin/http/docker-compose.yml',
])
cls.compose.start()
```
=> Support specifying multiple docker-compose.yml files

testcontainers/mongodb.py, tests/test_db_containers.py
First thanks for the library :)
I figured that the MongoDB container doesn't actually configure the username and password, so I added that it works
=> Fixed MongoDbContainer to actually use username and password

README.rst, testcontainers/localstack.py, tests/test_localstack.py
This PR adds an equivalent to the testcontainers-java Localstack container.
This is simpler than the Java version because a simple edge port was introduced in version 0.11.0. 
This should fix #33.
=> Add Localstack container support

example.py, requirements/3.5.txt, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, setup.py, testcontainers/compose.py, testcontainers/core/container.py, testcontainers/core/utils.py, testcontainers/core/waiting_utils.py
This PR proposes some changes for discussion.
I really enjoy using testcontainers and have used them in both Go and Java. In my opinion, there are some things missing or out of scope for this python implementation.
1. It is bad practice to use plain `print()` inside of python modules and one should always use the `logging` module so the end user can decide for himself if and what messages are of interest and should be logged.
2. In my opinion, the use-case for this kind of library clearly is integration testing in CI environments. Under this assumption I think purely cosmetic features like spinners and colored text are not required and only add dependencies.
Let me know your point on this.
Best, Roman
=> Add logging, remove crayon and blindspin

testcontainers/redis.py
Support decode_responses setting
=> [RedisContainer] Support decode_responses setting

.github/workflows/main.yml, .github/workflows/pypi-release.yml, .travis.yml
Closes #71
This PR adds 2 GitHub workflows:
1. `main` - regular push events
1. `pypi-release` - releasing the tagged version to PyPi
The release workflow is triggered by pushing any tag like `v*` but GitHub actions support [release events](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#publishing-to-package-registries) which might be considered as well.
Please, let me know about your thoughts regarding this PR so I could adjust its logic.
=> Add GitHub actions

testcontainers/compose.py, tests/.env.test, tests/docker-compose-3.yml, tests/test_docker_compose.py
This PR addresses #134 and is covered by a test case. I am contributing to open source for the first time so let me know if there is anything else required to successfuly pull.
=> Support passing custom env-file to DockerCompose

testcontainers/postgres.py
At the moment using a host other than localhost will fail because generic.py line 26 calls self.get_connection_url() without a host param which defaults to localhost.
This PR corrects this by setting host to None per default. The host will then correctly be assigned in _create_connection_url using get_container_host_ip.
=> Host always set to `localhost`

README.rst
Update a lingering link in the readme from markdown syntax to rst.
=> Fix readme link syntax

testcontainers/oracle.py
Fixes #105
Confirmed `test_docker_run_oracle` succeeds in my environment.
=> Add missing _configure to OracleDbContainer

README.rst, docs/database.rst, requirements.in, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt, setup.py, testcontainers/clickhouse.py, tests/test_db_containers.py
Added a testcontainer for the ClickHouse database.
=> Added ClickHouse support

testcontainers/elasticsearch.py
When I use `ElasticsearchContainer` class I get a "DeprecatedWarning: Elastic**S**earchContainer is deprecated" message which is wrong. This PR fixes this.
=> Fix deprecation warning message for `ElasticsearchContainer`

testcontainers/compose.py, tests/test_docker_compose.py
This PR adds a method that reaches out to docker-compose to execute a command in a service container.
~~I'm open to suggestions, in particular on the return type. Having a 3 tuple undocumented seems like it may be unintuitive to understand, but there seems to already be precedent in the `get_logs` method above, and not seeing method docstrings there to document it.~~
This was an old PR and I see there is some precedence for docstrings now, added a docstring as well
Thanks
=> Add compose exec_in_container method

setup.py, testcontainers/postgres.py
I've found installing `psycopg2` driver on MacOS Big Sur being too complicated: I didn't want to install `postgres` headers nor was I able to use the `-binary` version of the package. 
I've decided to use pure-python driver, but wasn't able to do so due to the driver being hardcoded. This PR addresses the limitation by adding an optional field to the constructor to override the driver.
I've added a `postgresql-pg8000` extra preset for convenience, but I'm happy to revert if you find it redundant ( https://github.com/testcontainers/testcontainers-python/pull/156/commits/756f3e127836a12741bb629fb3c7e459b930bd94 ).
=> Support specifying postgresql drivers

testcontainers/core/waiting_utils.py
Fixes #192
This PR reduces the log level for exceptions which occur while waiting for the Kafka broker to come up.
@tillahoffmann recommend this solution.
=> Reduce log level to prevent log file pollution

testcontainers/core/waiting_utils.py
Minor change to logging while caught in the "connection retry loop" as per [this comment](https://github.com/testcontainers/testcontainers-python/issues/206#issuecomment-1103026320) in [this issue](https://github.com/testcontainers/testcontainers-python/issues/206). Feel free to approve or reject at your leisure.
=> added logging of attempt no. while attempting to connect to container

requirements.in, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt, setup.py, testcontainers/core/generic.py, tests/test_db_containers.py
Fix too specific transient exception
`OperationalError` inherits from `DBAPIError`.
`pg8000` driver raises `InterfaceError` which also inherits form `DBAPIError`
```
sqlalchemy.exc.InterfaceError: (pg8000.exceptions.InterfaceError) network error on read
(Background on this error at: https://sqlalche.me/e/14/rvf5)
```
=> Add support for pg8000 postgres driver

.github/workflows/main.yml, README.rst, docs/conf.py, docs/database.rst, requirements.in, requirements/3.10.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt, setup.py, testcontainers/arangodb.py, tests/test_arangodb.py
ArangoDB -> https://www.arangodb.com
=> Add ArangoDB Container support

testcontainers/arangodb.py
Minor changes to let `None` default to environment variables and `True/False` to be used as is. Cf. #221.
=> Fix None/True/False handling in Arango.

testcontainers/core/container.py, testcontainers/core/docker_client.py
DockerClient.port() fails when called too quickly (from DockerContainer.get_exposed_port) after container start. Wrap DockerContainer.get_exposed_port in wait_container_is_ready() and change DockerClient.port to raise ConnectionError so that it can be caught and retried.
=> Catch and retry DockerClient.port() 

testcontainers/elasticsearch.py, tests/test_elasticsearch.py
=> Support Elasticsearch 8.x

testcontainers/arangodb.py, testcontainers/compose.py, testcontainers/elasticsearch.py, testcontainers/google/pubsub.py, testcontainers/keycloak.py, testcontainers/mssql.py, testcontainers/mysql.py, testcontainers/oracle.py, testcontainers/selenium.py, tests/test_nginx.py
These are style fixes from autopep8.
Since I didn't see black configured, I used a less opinionated tool.
Suggestions to change our code to be formatted using black are welcome though.
=> Run autopep8 to format the code

testcontainers/kafka.py, tests/test_kafka.py
Default version is already tested with the 2 other tests of the test suite, so I just added a test starting confluentinc/cp-kafka:7.1.3 with a message roundtrip.
=> Make kafka testcontainer compatible with confluentinc/cp-kafka:7.1.3

testcontainers/mongodb.py
Added port_to_expose argument on __init__ to configure MongoDB with different exposed ports
=> Configurable MongoDB exposed port

.github/workflows/main.yml, README.rst, requirements.in, requirements/3.10.txt, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt, setup.py, testcontainers/azurite.py, tests/test_azurite.py
Pull request to add azurite module. https://hub.docker.com/_/microsoft-azure-storage-azurite
=> Add azurite module

testcontainers/mysql.py
Currently `MySqlContainer` does not pass `kwargs` to its base class, so we cannot customize docker client's timeout. This PR enables the users of `MySqlContainer` to set docker client's configurations via `docker_client_kw`.
Context:
We encountered read timeout errors during creation of mysql containers in our CI:
```
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=2375): Read timed out. (read timeout=60)
```
We are still not sure what's the cause, but our current guess is that it's simply due to slow network.
=> Pass `**kwargs` from MySqlContainer constructor to DbContainer constructor

testcontainers/clickhouse.py
Fixes behavior from #257 when `with_bind_ports` is not working
=> Move `self.with_exposed_ports` to initializer

README.rst, setup.py
The requirements for Python 3.6 were already deleted in [this commit](https://github.com/testcontainers/testcontainers-python/commit/4786acc4dbaacc4aa27fd5c71e30ffea8443e4b3) but some small changes are needed to remove the complete Python 3.6 support.
#237
=> Removed Python 3.6 support

testcontainers/core/container.py, tests/test_core/test_docker_in_docker.py
In situations where the `DOCKER_HOST` env variable is set, `DockerContainer.get_container_host_ip()` returned either the gateway ip or the bridge ip instead of the actual container host ip. This caused connection issues in a docker-in-docker context, see #217. 
The `DockerContainer.get_container_host_ip()` function now uses the container ip whether the `DOCKER_HOST` variable is set in the environment. This should fix docker-in-docker situations while leaving other scenarios in a working state. Additionally, a test has been added that attempts to simulate a docker-in-docker situation. 
This PR is not intended to be anything more than a workaround for the current docker-in-docker issue (#217). I've intentionally kept the size and scope of the PR small to avoid making this a PR to fix all …
=> Workaround for docker-in-docker

setup.py
Some package managers (e.g. poetry) may enforce PEP 440 even when installing development-only version. This change supports such a use case.
=> make dev version PEP 440 compatible

neo4j/testcontainers/neo4j/__init__.py
The driver offers an API specifically crafted to test if it can successfully connect. This tends to exchange less data than a dummy query and hence should be slightly faster.
See also https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Driver.verify_connectivity
=> Neo4j: verify_connectivity for connection test

requirements.in, requirements/3.10.txt, requirements/3.11.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
=> Remove `codecov` requirement.

google/setup.py, google/testcontainers/google/pubsub.py, google/tests/test_google.py, requirements/3.10.txt, requirements/3.11.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt
☝️ 
Closes #209. Should allow #331 to pass because the outdated dependency is removed.
=> Update google-cloud-pubsub to major version 2.

Makefile
Avoids tests accidentally passing as in #320 because `pytest-asycnio` is missing.
=> Raise error on unknown marker.

.devcontainer/devcontainer.json, .gitignore, README.rst
Adds pre-configured support for GitHub Codespaces and local development using dev containers.
Makes maintenance, contributions and reviewing PRs easier, since it does not required developers to maintain a permanent local development environment (which is a bit more challenging, given the current approach of managing dependencies).
=> Add support for Codespaces

.github/workflows/ci-community.yml
Fixes an issue with the usage of https://github.com/tj-actions/changed-files.
Without a checkout, it breaks on `main`. This re-introduces that push to main.
=> fix: changed files breaks on main

core/testcontainers/core/container.py, core/testcontainers/core/docker_client.py, core/tests/test_core.py, pyproject.toml
Fixes #399. Applied a bit of defensive coding and attempted to create some tests for it, however reproducing it with a local dev machine is not easy. I did my best to reproduce the issue with garbage collection in the new test.
=> fix: flaky garbage collection resulting in testing errors

.devcontainer/commands/post-create-command.sh, .devcontainer/devcontainer.json
Following discussions here - https://github.com/testcontainers/testcontainers-python/issues/430
As well as looking at recent changes. It seems as though the devcontainer workflow is broken.
This PR will get you a working(?) install.
**From within the container**
```
vscode ➜ /workspaces/testcontainers-python (feature/poetry-devcontainers) $ poetry shell
Spawning shell within /home/vscode/.cache/pypoetry/virtualenvs/testcontainers-_53phrdA-py3.11                                                                          
```
Core tests passed.
```
(testcontainers-py3.11) vscode ➜ /workspaces/testcontainers-python (feature/poetry-devcontainers) $ make tests
poetry run pytest -v --cov=testcontainers.core core/tests
================================================================================ …
```
=> Integrate poetry into devcontainers

pyproject.toml
Set the version to the latest actual release candidate done by @alexanderankin.
In the first release-please PR #433 , we're not setting the version on the `pyproject.toml`, suspecting that it still works, but want to prove there are no issues with the automation.
The easiest proof of this is to set the value in the file to the actual release candidate. `release-please` in the future will be able to do release candidates by running `release-please` from the command line (documentation to be made on this)
=> fix(release): prove that the release process updates the version

modules/elasticsearch/tests/test_elasticsearch.py
- updated the image versions used for tests with the latest supported tags: https://hub.docker.com/_/elasticsearch
- fixes https://github.com/testcontainers/testcontainers-python/issues/452
=> fix: failing tests for elasticsearch on machines with ARM CPU

modules/mongodb/testcontainers/mongodb/__init__.py
we were using this code to test if it was online or not:`MongoClient(self.get_connection_url())`, but that doesn't actually perform any connection, instead you have to do something like:
```python
@wait_container_is_ready()
def _connect(self):
client = self.get_connection_client()
client.admin.command('ismaster')
```
thanks to @smparekh for pointing this out, in his PR:
https://github.com/testcontainers/testcontainers-python/pull/80/files#diff-cf09f76f44db0af04c58ddb456ccae39f7e29ce1d9208acd5f514c0a7dccb646R78
this PR implements the workaround described in the PR:
```python
@pytest.fixture(scope="session")
def test_client():
mongo_container = MongoDbContainer("mongo:4").start()
wait_for_logs(mongo_container, 'waiting for connections on port 27017')
...
=> fix(mongodb): waiting for container to start (it was not waiting at all before?)

core/testcontainers/core/docker_client.py
Strip whitespaces from key and value after reading `~/.testcontainers.properties`. The way TCD writes this file, the `=` will be surrounded by whitespaces, e.g.:
```
kiview@kay ~ % cat .testcontainers.properties
tc.host = tcp://127.0.0.1:59499
testcontainers.reuse.enable = true
```
Adds Plug&Play support for Testcontainers Desktop and Testcontainers Cloud.
Run any kind of tests that involve creating and starting containers, while Testcontainers Desktop is running. Testcontainers Desktop should be used and hence started containers can be seen in the Testcontainers Cloud dashboard.
=> fix(configuration): strip whitespaces when reading .testcontainers.properties

.github/release-please-config.json
remove the bootstrap sha from `release-please` since we're now bootstrapped - this will enable the tool to check for the latest release PR instead of looking at the SHA
=> chore(release): completely remove bootstrap-sha as we're bootstrapped

modules/arangodb/testcontainers/arangodb/__init__.py, modules/arangodb/tests/test_arangodb.py
- updated arangodb image version which now supports ARM CPUs
- skipping test for legacy version on ARM CPU
fixes https://github.com/testcontainers/testcontainers-python/issues/449
=> fix(arangodb): tests to pass on ARM CPUs - change default image to 3.11.x where ARM image is published

core/testcontainers/compose/compose.py
=> fix(core): raise an exception when docker compose fails to start #258

modules/keycloak/testcontainers/keycloak/__init__.py, modules/keycloak/tests/test_keycloak.py
- jboss/keycloak is discontinued, adapting the official Docker image: https://quay.io/repository/keycloak/keycloak
- switched to the latest image version with ARM support
fixes https://github.com/testcontainers/testcontainers-python/issues/451
fixes https://github.com/testcontainers/testcontainers-python/issues/483
=> fix(keycloak): tests on aarch64, use image from [jboss -> quay], change supported version [16+ -> 18+]

index.rst
The .github/workflows/main.yml has already been removed. This caused the badge on the tutorial page not to be displayed, so it has been removed from index.rst.
https://testcontainers-python.readthedocs.io/en/latest/README.html
=> fix(docs): update the non-existent main.yml badge

core/testcontainers/core/container.py, core/tests/test_ryuk.py
fix #489 , supercede #491, #498
=> fix(core): use auto_remove=True with reaper instance

modules/kafka/testcontainers/kafka/__init__.py, poetry.lock, pyproject.toml
Use `wait_for_logs` to wait for startup instead of waiting for successful connection via kafka-python. Also removes the dependency on kafka-python.
Closes #351
=> fix(kafka): wait_for_logs in kafka container to reduce lib requirement

modules/keycloak/testcontainers/keycloak/__init__.py, modules/keycloak/tests/test_keycloak.py
As decided to support v18.0 image or newer, we should use these dedicated API endpoints to determine container readiness. These endpoints became introduced with v18.0.
=> fix(keycloak): container should use dedicated API endpoints to determine container readiness

core/testcontainers/core/docker_client.py
Set User-Agent in format `tc-python/<version>`, `version` value is coming from `pyproject.toml`.
The `User-Agent` header will allow to identify Testcontainers language implementation and the specific version. Also, track the usage of the library.
=> feat(client): Add custom User-Agent in Docker client as `tc-python/<version>`

core/testcontainers/compose/compose.py
fix #306
the original request was to remedy tc-python's dependency on docker-compose.
this is something totally different but its what was asked for, so oh well. ¯\_(ツ)_/¯.
=> fix(core): allow setting docker command path for docker compose

modules/google/testcontainers/google/pubsub.py
=> fix: pass updated keyword args to Publisher/Subscriber client in google/pubsub #161

modules/google/README.rst, modules/google/testcontainers/google/__init__.py, modules/google/testcontainers/google/datastore.py, modules/google/tests/test_google.py, poetry.lock, pyproject.toml
Expands the google module with a DatastoreContainer using the beta Datastore emulator using the same image as the PubSubContainer.
Im already using a local copy of this in production. It would be nice to not have to support copy paste solutions and instead see it added to the google module. This is my first PR so please let me know what I need to do to get this over the line. Thanks.
Looks like @tillahoffmann wrote the original PubSub emulator container
=> fix(google): add support for Datastore emulator

README.md, core/testcontainers/core/config.py, core/testcontainers/core/container.py, core/tests/test_ryuk.py, index.rst
- Re-enables the Ryuk test suite
- Bumps Ryuk container image from 0.5.1 - > 0.7.0
- Add env variable `RYUK_RECONNECTION_TIMEOUT` (As documented in the [official Ryuk repo](https://github.com/testcontainers/moby-ryuk?tab=readme-ov-file#ryuk-configuration))
=> fix(ryuk): Enable Ryuk test suite. Ryuk image 0.5.1 -> 0.7.0. Add RYUK_RECONNECTION_TIMEOUT env variable

.github/workflows/ci-community.yml, .github/workflows/ci-core.yml, .github/workflows/ci-lint.yml, .github/workflows/docs.yml, .github/workflows/pr-lint.yml, .github/workflows/release-please.yml
- Fixed inconsistencies for community module test runs: using all supported Python versions
- Pinned runner version (best practice)
fixes https://github.com/testcontainers/testcontainers-python/issues/482
=> fix: inconsistent test runs for community modules

index.rst, modules/chroma/README.rst, modules/chroma/testcontainers/chroma/__init__.py, modules/chroma/tests/test_chroma.py, poetry.lock, pyproject.toml
=> fix: add chroma container

core/testcontainers/core/container.py, core/testcontainers/core/docker_client.py
Improves type hints for type checking in a common use cases:
```python
with MySqlContainer("mysql:8").with_env("some", "value") as mysql:
url = mysql.get_connection_url()  # get_connection_url would previously be an unknown member here
```
And, also improved type hinting for the custom `DockerClient`'s `run` command, where the linter no longer reports an error due to missing parameter types:
```python
DockerClient.run("nginx")  # Previously this would report "Argument missing for parameter "image"
```
=> fix(core): Improving typing for common container usage scenarios

.pre-commit-config.yaml, core/testcontainers/core/docker_client.py, modules/influxdb/testcontainers/influxdb.py, modules/mongodb/testcontainers/mongodb/__init__.py, modules/mssql/testcontainers/mssql/__init__.py, modules/mysql/testcontainers/mysql/__init__.py, modules/mysql/tests/test_mysql.py, modules/opensearch/testcontainers/opensearch/__init__.py, modules/oracle-free/testcontainers/oracle/__init__.py, modules/rabbitmq/testcontainers/rabbitmq/__init__.py
Changed pre-commit config. Some files
became re-formatted.
=> chore(codestyle): switch to `ruff` from `black` for code formatting

README.md
I added the following badges:
- Poetry
- Ruff
- Supported Python versions
- Workflow runs
=> docs: Added badges to README.md

core/testcontainers/core/config.py, core/testcontainers/core/container.py, core/testcontainers/core/docker_client.py, core/testcontainers/core/labels.py, core/testcontainers/core/waiting_utils.py, core/tests/test_ryuk.py, modules/arangodb/testcontainers/arangodb/__init__.py, modules/k3s/testcontainers/k3s/__init__.py, modules/neo4j/testcontainers/neo4j/__init__.py, modules/postgres/testcontainers/postgres/__init__.py, modules/qdrant/testcontainers/qdrant/__init__.py
=> fix(core): make config editable to avoid monkeypatching.1

modules/kafka/testcontainers/kafka/__init__.py, modules/kafka/tests/test_kafka.py
v5.4.3 was not supporting ARM CPUs. Removed an obsolet test.
Fixes https://github.com/testcontainers/testcontainers-python/issues/450
=> fix: tests for Kafka container running on ARM64 CPU

core/testcontainers/core/docker_client.py, index.rst
Resolves #383 
This PR aims to unify the configuration for the Testcontainer Hostvariable as it is in [Java](https://java.testcontainers.org/features/configuration/#customizing-docker-host-detection) and [Dotnet](https://dotnet.testcontainers.org/custom_configuration/) (and potentially others).
=> fix(core): add TESTCONTAINERS_HOST_OVERRIDE as alternative to TC_HOST

core/testcontainers/core/generic.py, modules/mongodb/tests/test_mongodb.py, modules/mssql/tests/test_mssql.py, modules/mysql/tests/test_mysql.py, modules/postgres/tests/test_postgres.py
**Changes**
Updated DbContainer to fix #547 by using `urllib.parse.quote`. I referenced sqlalchemy's implementation, but have not imported the library.
I have chosen to make this behaviour occur at all times (can't opt in / out), as it is common, if not the standard for these urls.
**Tests**
Since DbContainer can't be tested on its own, I put the tests across various database containers. I have pasted the below as comment in the test files for the listed modules:
```python
```
Note the discussion recommended me to test with oracle, but I was unable to spin the container up locally (even with colima), so opted to replace it with mongodb.
Is there a template for PRs for the core library? I am unable to find one so have opted the above format. Please let me know if I have missed anything in …
=> fix: url quote passwords

modules/keycloak/testcontainers/keycloak/__init__.py
This PR adds an option to start a keycloak container with importing one or more realms. This mirrors a feature present in the java keycloak testcontainer.
=> fix(keycloak): add realm imports

core/testcontainers/core/generic.py, modules/mysql/testcontainers/mysql/__init__.py, modules/mysql/tests/seeds/01-schema.sql, modules/mysql/tests/seeds/02-seeds.sql, modules/mysql/tests/test_mysql.py
Ref #541.
New capability of "seeding" a db container using image's support for /docker-entrypoint-initdb.d/ folder.
Using the "transferable" system, borrowed from Kafka. 
Updates DbContainer to have a new (NOOP-default) `_transfer_seed()` method, run after `_start()` and before `_connect()`, to allow the folder transfer.
Currently implemented only in MySQL, but extensible to others that use the `/docker-entrypoint-initdb.d/` system.
=> fix(mysql): Add seed support in MySQL

core/tests/compose_fixtures/basic/docker-compose.yaml, core/tests/compose_fixtures/port_multiple/compose.yaml, core/tests/compose_fixtures/port_single/compose.yaml
This would address #570
Removing the version from the compose.yaml files used in tests.
Please see https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
=> fix(core): remove version from compose tests

modules/selenium/testcontainers/selenium/__init__.py, modules/selenium/testcontainers/selenium/video.py, modules/selenium/tests/test_selenium.py
Support video in selenium testcontainer.
Changes made:
- Added network to default container.
- Added video to selenium by write `with_video`.
=> fix: Add selenium video support #6

core/testcontainers/core/config.py, core/testcontainers/core/container.py
https://github.com/testcontainers/testcontainers-python/issues/557 -  trying to solve this issue by adding types.
=> fix: added types to exec & tc_properties_get_tc_host

core/testcontainers/compose/compose.py
#358 
not sure if this is the right solution
=> fix: on windows, DockerCompose.get_service_host returns an unusable "0.0.0.0" - adjust to 127.0.0.1

modules/keycloak/testcontainers/keycloak/__init__.py
With the option to import keycloak realms, introduced with #565, the[_configure()](https://github.com/testcontainers/testcontainers-python/blob/78b6f0ecb15e8cba687eb4588c5ce19ca32208bc/modules/keycloak/testcontainers/keycloak/__init__.py#L57) method is called twice. Once it is called in the [start()](https://github.com/testcontainers/testcontainers-python/blob/78b6f0ecb15e8cba687eb4588c5ce19ca32208bc/modules/keycloak/testcontainers/keycloak/__init__.py#L83) method of keycloak itself and then it is called a second time in the [start()](https://github.com/testcontainers/testcontainers-python/blob/78b6f0ecb15e8cba687eb4588c5ce19ca32208bc/core/testcontainers/core/container.py#L90) method of DockerContainer. This wasn't an issue so far. But if a realm shall be imported (self.has_realm_import …
=> fix(keycloak): realm import

index.rst
Following #566 - Private registry, adding the relevant doc so the usage will be clear and (hopefully) reachable.
=> docs(main): Private registry

index.rst
Fix some issues with the private registry instructions:
- issue with the link to official documentation
- convert all relevant blocks to code-block
- fix some typos
=> docs: Update private registry instructions

modules/cockroachdb/README.rst, modules/cockroachdb/testcontainers/__init__.py, modules/cockroachdb/testcontainers/cockroachdb/__init__.py, modules/cockroachdb/tests/test_cockroachdb.py, poetry.lock, pyproject.toml
Adds [Cockroach DB] (https://www.cockroachlabs.com/) module to use with Test containers
I had done this previously under https://github.com/testcontainers/testcontainers-python/pull/281, but opted to just redo it rather than try to rebase all the things.
- [] Add a line `[feature name]` to the list of components in the  GitHub Action workflow in `.github/workflows/main.yml` to run tests, build, and publish your package when pushed to the `main` branch.
=> fix: Add Cockroach DB Module to Testcontainers

core/testcontainers/core/version.py, core/tests/test_version.py, modules/kafka/testcontainers/kafka/__init__.py, modules/kafka/tests/test_kafka.py
Following a similar strategy as several other testcontainers implementations, this PR introduces the possibility to run Kafka in KRAft mode.
```py
with KafkaContainer().with_kraft() as container:
```
=> fix(kafka): Add Kraft to Kafka containers

core/testcontainers/core/image.py, core/tests/test_core.py
=> feat(core): allow custom dockerfile path for image build and bypassing build cache

modules/ollama/README.rst, modules/ollama/testcontainers/ollama/__init__.py, modules/ollama/tests/test_ollama.py, poetry.lock, pyproject.toml
- Added a new class OllamaContainer with few methods to handle the Ollama container.
- The `_check_and_add_gpu_capabilities` method checks if the host has GPUs and adds the necessary capabilities to the container.
- The `commit_to_image` allows to save somehow the state of a container into an image so that we can reuse it, especially for the ones having some models pulled.
- Added tests to check the functionality of the new class.
> Note: I inspired myself from the java implementation of the Ollama module.
Fixes #617
=> feat(core): Add support for ollama module

core/testcontainers/compose/compose.py, core/tests/compose_fixtures/basic_multiple/docker-compose.yaml, core/tests/test_compose.py
The command would otherwise stop/down all services, not just the services the instance itself started.
Useful for e.g. one fixture per service, and you want different scopes for the services.
=> feat(core): DockerCompose.stop now stops only services that it starts (does not stop the other services)

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/new-container.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE/new_container.md, Dockerfile, Makefile, README.md, index.rst
Document how to contribute, with initial focus on making local development smooth.
=> docs(contributing): add contribution and new-container guide 

.github/settings.yml, modules/mailpit/README.rst, modules/mailpit/testcontainers/mailpit/__init__.py, modules/mailpit/tests/test_mailpit.py, poetry.lock, pyproject.toml
Fixes #626 
as we make use of this for detecting Semantic Versioning changes.
- Your module follows [PEP 420](https://peps.python.org/pep-0420/) with implicit namespace packages
(if unsure, look at other existing community modules)
- Your package namespacing follows `testcontainers.<modulename>.*`
and you DO NOT have an `__init__.py` above your module's level.
- Your module has it's own tests under `modules/*/tests`
- Your module has a `README.rst` and hooks in the `.. auto-class` and `.. title` of your container
- Implement the new feature (typically in `__init__.py`) and corresponding tests.
- it is declared under `tool.poetry.packages` - see other community modules
- it is declared under `tool.poetry.extras` with the same name as your module name,
we still prefer adding _NO EXTRA …
=> fix(modules): Mailpit Container

.github/settings.yml, modules/sftp/README.rst, modules/sftp/testcontainers/sftp/__init__.py, modules/sftp/tests/test_sftp.py, poetry.lock, pyproject.toml
Fixes #628
as we make use of this for detecting Semantic Versioning changes.
- Your module follows [PEP 420](https://peps.python.org/pep-0420/) with implicit namespace packages
(if unsure, look at other existing community modules)
- Your package namespacing follows `testcontainers.<modulename>.*`
and you DO NOT have an `__init__.py` above your module's level.
- Your module has it's own tests under `modules/*/tests`
- Your module has a `README.rst` and hooks in the `.. auto-class` and `.. title` of your container
- Implement the new feature (typically in `__init__.py`) and corresponding tests.
- it is declared under `tool.poetry.packages` - see other community modules
- it is declared under `tool.poetry.extras` with the same name as your module name,
we still prefer adding _NO EXTRA …
=> fix(modules): SFTP Server Container

core/testcontainers/core/docker_client.py, core/testcontainers/core/network.py, core/tests/test_network.py
This PR adds `create` method to the `Network` class to enable a non-context-manager usage.
Fixes #627
=> fix(network): Now able to use Network without context, and has labels to be automatically cleaned up (#627)

modules/kafka/testcontainers/kafka/__init__.py, modules/kafka/tests/test_kafka.py
=> fix(kafka): add a flag to limit to first hostname for use with networks

core/testcontainers/core/auth.py, core/testcontainers/core/docker_client.py, core/testcontainers/core/utils.py, core/tests/test_auth.py, core/tests/test_docker_client.py
Continuing #562, got some feedback regarding an issue with unsupported use cases.
In this PR we will try to:
1. Map the use cases
2. Raise a warning regarding unsupported uses cases (hopefully they will be added later)
3. Address/Fix the issue where unsupported JSON schema for `DOCKER_AUTH_CONFIG` leads to an error
As always any feedback will be much appreciated.
_Please note this PR does not implement all use-cases just does a better job at preparing and handling them for now_
=> fix(core): Improve private registry support (tolerate not implemented fields in DOCKER_AUTH_CONFIG)

modules/aws/README.rst, modules/aws/testcontainers/aws/__init__.py, modules/aws/testcontainers/aws/aws_lambda.py, modules/aws/tests/lambda_sample/Dockerfile, modules/aws/tests/lambda_sample/lambda_function.py, modules/aws/tests/test_aws.py, poetry.lock, pyproject.toml
As part of the effort described, detailed and presented on https://github.com/testcontainers/testcontainers-python/pull/559
This is the 4th (and final in this track) PR that should provide support for AWS Lambda containers.
This module will add the ability to test and run Amazon Lambdas (using the built-in runtime interface emulator)
For example:
```python
from testcontainers.aws import AWSLambdaContainer
from testcontainers.core.waiting_utils import wait_for_logs
from testcontainers.core.image import DockerImage
with DockerImage(path="./modules/aws/tests/lambda_sample", tag="test-lambda:latest") as image:
with AWSLambdaContainer(image=image, port=8080) as func:
response = func.send_request(data={'payload': 'some data'})
assert response.status_code == 200
assert "Hello from AWS Lambda …
```
=> feat(new): Added AWS Lambda module

modules/rabbitmq/testcontainers/rabbitmq/__init__.py, modules/rabbitmq/tests/test_rabbitmq.py
Adds a `vhost` parameter to the RabbitMQContainer constructor that allows the `RABBITMQ_DEFAULT_VHOST` [environment variable](https://www.rabbitmq.com/docs/configure#supported-environment-variables) to be modified.
Subsequently `vhost` is then also used inside the `get_connection_params` method for the `pika` connection parameters, which is used to test if the container is ready.
=> fix(rabbitmq): add `vhost` as parameter to RabbitMqContainer

conf.py, modules/selenium/testcontainers/selenium/__init__.py
=> fix(selenium): add Arg/Options to api of selenium container

core/testcontainers/compose/compose.py, core/tests/test_compose.py, poetry.lock, pyproject.toml
This PR add a new function to the `testcontainers.compose.DockerComposer` class, `get_config` which use `docker compose config` command for resolving and returning the actual docker compose configuration.
This can be useful for example if you want to retrieve a connection string you pass to your app in your docker compose in order to connect to your database service instead of copy pasting it from your compose file into your tests.
Also note thats its way easier to rely on docker compose config to get you the config than trying to manually find, read and merge compose files in specified context (I tried it first ...).
About the tests I mostly ensured the docker compose command was as expected. This is because the config produced by the docker compose can not always reflect exactly what is …
=> feat(compose): add ability to get docker compose config

modules/db2/README.rst, modules/db2/testcontainers/db2/__init__.py, modules/db2/tests/test_db2.py, modules/mongodb/tests/test_mongodb.py, modules/mysql/tests/test_mysql.py, modules/postgres/tests/test_postgres.py, poetry.lock, pyproject.toml
Add Db2 support https://github.com/testcontainers/testcontainers-python/issues/672.
=> fix: Add Db2 support

core/testcontainers/core/container.py, core/tests/test_network.py
fixes https://github.com/testcontainers/testcontainers-python/issues/645 - network should be attached as the container is started, not as a post-start action. This will make sure port binding and exposing works correctly.
=> feat: refactor network setup

core/testcontainers/core/waiting_utils.py
Addresses my suggestion made in [issue 681](https://github.com/testcontainers/testcontainers-python/issues/681).
This PR adds a flag that checks is the status is not `running` and raises a `RuntimeError` to avoid waiting for logs after the container already has exited. The idea is to save wait time when there is a long startup time in case the container fails early.
```python
from testcontainers.core import container, waiting_utils
if __name__ == "__main__":
waiting_utils.wait_for_logs(
container.DockerContainer("flyway/flyway").start(),
r"Successfully applied \d+ migrations to schema",
timeout=10,
raise_on_exit=True,
)
```
=> fix: wait_for_logs can now fail early when the container stops

core/testcontainers/core/container.py, modules/mssql/testcontainers/mssql/__init__.py, modules/mssql/tests/test_mssql.py
=> fix(mssql): use glob to find mssql-tools folder since it moves

modules/generic/tests/samples/fastapi/Dockerfile
[FastAPI](https://github.com/fastapi/fastapi) now requires to provide the specific suit for the install, as a result one of the doctest (part of the `generic module`) got broken and its Dockerfile sample needed to be updated.
=> fix: Update the FastAPI install on genric module doctest samples

modules/opensearch/testcontainers/opensearch/__init__.py, modules/opensearch/tests/test_opensearch.py
Opensearch has made an initial admin password mandatory since version 2.12 as can be read in the [changelogs](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.12.0.md).
The open search module in test containers-python does not pass in this additional flag and current compatibility with open search >= 2.12 is broken .
This MR adds compatibility with open search >= 2.12 by adding the inidial_admin_password flag to the docker environment
=> fix(opensearch): add support for admin_password in >= 2.12

modules/keycloak/testcontainers/keycloak/__init__.py, modules/keycloak/tests/test_keycloak.py
Keycloak changed the health endpoint to a separate "management port" starting version 25.0.0 as can be read in the [changelogs](https://www.keycloak.org/docs/25.0.0/release_notes/#management-port-for-metrics-and-health-endpoints).
The keycloak module in testcontainers-python uses this endpoint for the readiness_probe. Currently compatibility with Keycloak >= 25 is broken.
This MR adds compatibility with Keycloak >= 25 by changing the readiness probe to do the following:
- Try the health endpoint on the management port
- If that gives a ConnectionError try the legacy health endpoint
An alternative approach would have been to create a separate LegacyKeycloakContainer class as has been done in other modules, however I think this unnecessarily complicates the user experience.
Additionally a …
=> fix(keycloak): Add support for Keycloak version >=25

core/testcontainers/core/config.py, core/testcontainers/core/utils.py
Supports: https://github.com/testcontainers/testcontainers-python/issues/305
Related : #691 
```bash
poetry run mypy --config-file pyproject.toml core/testcontainers/core/config.py core/testcontainers/core/utils.py
Success: no issues found in 2 source files
```
=> fix(core): Typing in config + utils

core/tests/test_config.py, core/tests/test_core.py, core/tests/test_image.py, core/tests/test_utils.py, core/tests/test_waiting_utils.py
Found some loss ends while working on fixing the typing.
The idea in this PR is to reorganize the tests to **better reflect** the use case (not all just in `test_core`)
This should help help avoid later issues when we fix more typing (allowing better isolation/management)
Also took this opportunity to **add missing tests** for `utils` and `config`
So now we have:
1. `test_image` - stripped from `test_core`
2. `test_waiting_utils` - stripped from `test_core`
3. a much cleaner `test_core`
4. `test_utils` - new
5. `test_config` - new
```bash
---------- coverage: platform linux, python 3.10.12-final-0 ----------
Name                                        Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------------- …
```
=> fix(core): Reorganize core tests and improve

.github/workflows/ci-core.yml
`upload-artifact` updated behavior: Hidden Files will be excluded by default 
https://github.com/actions/upload-artifact/issues/602
Need to include 
```yaml
include-hidden-files: true
```
=> fix(tests): Missing artifacts (include-hidden-files)

modules/postgres/testcontainers/postgres/__init__.py, modules/postgres/tests/test_postgres.py
logs may be dependent on a particular locale
fixes: #703,  #695
=> fix: postgres use psql instead of logs

Dockerfile, Makefile, core/testcontainers/core/config.py, core/testcontainers/core/container.py, core/testcontainers/core/docker_client.py, core/testcontainers/core/utils.py, core/tests/conftest.py, core/tests/test_config.py, core/tests/test_container.py, core/tests/test_docker_client.py, core/tests/test_docker_in_docker.py, core/tests/test_ryuk.py, core/tests/test_utils.py, modules/mysql/tests/test_mysql.py, modules/postgres/tests/test_postgres.py, pyproject.toml
closes #475 
One step closer to solve #517
Replaces #622 
According to the [data collected](https://github.com/testcontainers/testcontainers-python/issues/475#issuecomment-2407250970) this should fix issues running testcontainers inside a container in almost all cases.
There is still an issue when running it within docker desktop, that is probably easily solved which checking for the existence of `host.docker.internal`.
But I have to recollect the data to ensure this, so this will be added at later point in time, as with with setting `-e TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal` an easy workaround exists as well.
=> fix(core): running testcontainer inside container

poetry.lock
This allows testcontainers to work with requests >= 2.32.0.
Fixes: https://github.com/testcontainers/testcontainers-python/issues/717
Link: https://github.com/docker/docker-py/issues/3256
Link: https://github.com/docker/docker-py/pull/3257
Link: https://github.com/docker/docker-py/issues/3256#issuecomment-2376439000
=> chore: Update docker to 7.1.0

core/testcontainers/core/waiting_utils.py
Attempt to fix another part of #715 , plus an optimization.
Based on #716 by @alexanderankin .
=> fix: update wait_for_logs to not throw on 'created', and an optimization

Makefile
they both have been replaced by proper `pytest` tests
follow up of #714
=> chore(core): remove test-dind and image makefile entries

modules/generic/testcontainers/generic/server.py
Used same wording as for modules/aws/testcontainers/aws/aws_lambda.py
=> docs: Documentation fix for ServerContainer

modules/vault/testcontainers/vault/__init__.py
While migrating from Docker Desktop to Rancher Desktop on macOS, I encountered an issue where container port forwarding to the host machine was taking a long time. This delay caused the health check to fail with the following error:
```python
self = <urllib.request.HTTPHandler object at 0x108683a70>
http_class = <class 'http.client.HTTPConnection'>
req = <urllib.request.Request object at 0x1087788f0>, http_conn_args = {}
host = 'localhost:32771', h = <http.client.HTTPConnection object at 0x108683fb0>
headers = {'Connection': 'close', 'Host': 'localhost:32771', 'User-Agent': 'Python-urllib/3.12'}
def do_open(self, http_class, req, **http_conn_args):
"""Return an HTTPResponse object for the request, using http_class.
http_class must implement the HTTPConnection API from http.client.
""" …
```
=> fix: Vault health check

.github/CONTRIBUTING.md
The previous link had '.github' twice in the path, as Github does not parse it as path from repo, but as path from current folder. Perhaps the contributing.md was previously at top level instead of .github folder.
The current link in main branch is: https://github.com/testcontainers/testcontainers-python/blob/main/.github/.github/ISSUE_TEMPLATE/new-container.md
=> chore: fix broken link in contributing.md

modules/generic/testcontainers/generic/server.py
There was a race condition here because the server hasn't always started before we send a request to it. This was causing a lot of unnecessary test failures.
This change makes use of `ServerContainer` much more reliable.
```
../../../Library/Caches/pypoetry/virtualenvs/<redacted>/lib/python3.12/site-packages/testcontainers/generic/server.py:70: in start
self._connect()
../../../Library/Caches/pypoetry/virtualenvs/<redacted>/lib/python3.12/site-packages/testcontainers/core/waiting_utils.py:59: in wrapper
return wrapped(*args, **kwargs)
../../../Library/Caches/pypoetry/virtualenvs/<redacted>/lib/python3.12/site-packages/testcontainers/generic/server.py:48: in _connect
with urlopen(url) as r:
/usr/local/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/ …
```
=> fix(generic): Also catch URLError waiting for ServerContainer

core/testcontainers/compose/compose.py, core/tests/compose_fixtures/profile_support/compose.yaml, core/tests/test_compose.py
Adds `profiles` support for docker compose.
I've had to use a workaround in a company project for compose profiles leading to multiple compose profile files. 
This should help by supporting profiles in compose which is a very handy feature when your service has some variety of ways to run (contextual, environmental, etc)
Without this, it's still possible to run profiles buy setting the `COMPOSE_PROFILES` env variable, but this is certainly cleaner and easier on test writing.
https://docs.docker.com/compose/how-tos/profiles/#assigning-profiles-to-services
=> feat(compose): support for setting profiles

core/tests/conftest.py
fix: #749
Replace using `subprocess.run` in the **dind** test with SDK to avoid the direct call to docker that enforces the developer to run _sudoless_ docker.
=> fix(tests): replace dind-test direct docker usage with sdk

core/testcontainers/core/labels.py, core/tests/test_labels.py
When invoking `.start()` multiple times on the same `DockerContainer` instance, the call fails with `ValueError: The org.testcontainers namespace is reserved for internal use` error.
Example code:
```
from testcontainers.core.container import DockerContainer
container = DockerContainer("alpine:latest").with_kwargs(labels={})
container.start()
container.stop()
container.start()
```
The fix is to update labels for the container in a copy of the user-provided dictionary, so that:
* the code doesn't mutate user structures
* avoid side effects, allowing for multiple .start() invocations
=> fix(core): multiple container start invocations with custom labels

modules/opensearch/testcontainers/opensearch/__init__.py
=> fix: Change env var disabling OpenSearch security plugin

core/tests/test_labels.py
Make sure the test covers the intended behaviour. Previously it was executing the create_labels function without actually verifying there are no side effects.
=> fix(core): create_label test

.github/workflows/ci-community.yml, modules/aws/testcontainers/aws/aws_lambda.py, modules/generic/testcontainers/generic/server.py
This will address the Security issue reported on #786
As recommended, `tj-actions/changed-files` was replace replaced with [path-filter](https://github.com/dorny/paths-filter)
=> fix(security): Update track-modules job 

core/testcontainers/socat/__init__.py, core/testcontainers/socat/socat.py, core/tests/test_socat.py
Add new SocatContainer at testcontainers module that
can be used along with other modules as a helper.
=> feat: Add SocatContainer

core/testcontainers/core/config.py, core/tests/test_config.py
fixes #537
Use docker_api to determine the `socket_path` (defined in [`UnixHTTPAdapter`](https://github.com/docker/docker-py/blob/db7f8b8bb67e485a7192846906f600a52e0aa623/docker/transport/unixconn.py#L55)).
Replaces: https://github.com/testcontainers/testcontainers-python/pull/710
=> fix(core): Determine docker socket for rootless docker

core/testcontainers/core/container.py
the `with_command` function can actually take an argument with type `list[str]`.
=> fix(core): change with_command type to include list of strings

core/testcontainers/core/config.py, core/tests/test_config.py
=> fix: use connection mode override function in config

core/testcontainers/core/image.py, core/tests/test_image.py
Fix: #706, https://github.com/testcontainers/testcontainers-python/pull/614
Now when using kwargs in the Image API, the params are passed correctly into the build
```python
with DockerImage(path=dir, tag="test", buildargs={"MY_ARG": "some_arg"}) as image:
```
Added relevant test + updated docstring to better reflect the usage
=> fix(core): Add kwargs to image build

core/testcontainers/compose/compose.py
closes #745 
if the docker compose command is provided, use that instead of default one.
=> fix(compose): use provided docker command instead of default

core/testcontainers/core/config.py, core/testcontainers/core/docker_client.py
Supports: https://github.com/testcontainers/testcontainers-python/issues/305
Related : https://github.com/testcontainers/testcontainers-python/pull/691 https://github.com/testcontainers/testcontainers-python/pull/692 #700 
Based on #504, kudos @alexanderankin 
```
poetry run mypy --config-file pyproject.toml core/testcontainers/core/docker_client.py 
Success: no issues found in 1 source file
```
Old
```
Error Summary                     
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ File Path                                 ┃ Errors ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ core/testcontainers/core/version.py       │ 12     │
│ core/testcontainers/core/docker_client.py │ 14     │
│ core/testcontainers/core/image.py         │ 17     │
│ …
```
=> fix(core): Typing in docker_client

.pre-commit-config.yaml, core/testcontainers/compose/__init__.py, core/testcontainers/compose/compose.py, core/testcontainers/core/config.py, core/testcontainers/core/docker_client.py, core/testcontainers/core/waiting_utils.py, core/testcontainers/socat/__init__.py, core/tests/conftest.py, core/tests/test_utils.py, modules/azurite/testcontainers/azurite/__init__.py, modules/generic/tests/conftest.py, modules/google/tests/test_google.py, modules/k3s/testcontainers/k3s/__init__.py, modules/mqtt/testcontainers/mqtt/__init__.py, modules/opensearch/testcontainers/opensearch/__init__.py, modules/scylla/tests/test_scylla.py, poetry.lock, pyproject.toml
TL;DR this is a cleanups and alignments
- Update pre-commit ruff version to latest + adaptations needed
- Fix some issues with the pyproject.toml file schemas.
1. `tool.poetry.source` requires URL [see](https://github.com/python-poetry/poetry/issues/3855)
2. `tool.ruff.lint` changed flake8-type-checking code [checkout](https://astral.sh/blog/ruff-v0.8.0)
3. `tool.mypy` doest not support `fast_module_lookup` in the TOML (Need to investigate more if we want to add it back)
=> chore(main): project fixes and updates

modules/rabbitmq/testcontainers/rabbitmq/__init__.py
This small PR fixes the pika pypi reference in RabbitMqContainer class page. 
Relevant page: https://testcontainers-python.readthedocs.io/en/latest/modules/rabbitmq/README.html
=> fix(rabbitmq): correct pika pypi reference

modules/registry/testcontainers/registry/__init__.py, modules/registry/tests/test_registry.py, pyproject.toml
=> fix(registry): module typed

core/tests/test_core_registry.py
Discovered on #810 
Fix original test implementation
=> fix(core): wait in test core registry

.github/workflows/ci-lint.yml, Makefile, core/testcontainers/core/config.py
1. leftovers from a previous mypy refactor
```python
core/testcontainers/core/config.py:42: error: Redundant cast to "str"  [redundant-cast]
socket_path = cast("str", socket_path)
```
Post fix:
```bash
#poetry run mypy --config-file pyproject.toml core
Success: no issues found in 36 source files
```
2. add mypy check to the CI under lint, also create a simple report if something is wrong.
=> fix: Enable mypy in the CI

core/testcontainers/core/config.py, core/testcontainers/core/waiting_utils.py
This config variable gets passed into `time.sleep`, which can work with ints and floats. Making this a float type allows polling intervals under a second, which can reduce startup times for containers that spin up very quickly.
I couldn't see any existing issue around this, and think it's probably only got a fairly small use case (but I do use it), so thought I'd throw up a PR as an easier way to just make the call on whether it's something you'd accept or not 🙇
=> fix(core): Make TC_POOLING_INTERVAL/sleep_time a float

core/testcontainers/core/config.py, core/tests/test_config.py
fix #864 
The environment variables were not overridden from the .testcontainers.properties file for ryuk variables. This causes the properties file to never actually be used. This commit detects the environment variable, and if unspecified falls back to the properties file, and if not specified, defaults to false
=> fix(core): improper reading of .testcontainers.properties

core/testcontainers/compose/compose.py
If docker_command_path is specified, 'compose' is not appended, which causes all of DockerCompose to not work. This issue was found when attempting to use podman.
=> fix(core): Added 'compose' in compose_command_property

core/testcontainers/compose/compose.py, core/testcontainers/core/container.py
Fixed some strange issues with the doctests on core:
=> fix(core): fix issues with doctests
