testcontainers/testcontainers-python

README.md, docs/index.rst, setup.py, tox.ini
=> Use extras for optional dependencies

Pipfile, Pipfile.lock, docs/google-cloud-emulators.rst, docs/index.rst, release-process.rst, setup.py, testcontainers/google/__init__.py, testcontainers/google/pubsub.py, tests/test_google.py
This PR ads a Google Cloud PubSub emulator container. See `tests/test_google.py` for an example.
=> Add Google Cloud PubSub emulator container.

.travis.yml, Pipfile, Pipfile.lock, docs/conf.py, setup.cfg, setup.py, testcontainers/compose.py, testcontainers/general.py, testcontainers/google/__init__.py, testcontainers/google/pubsub.py, testcontainers/mongodb.py, testcontainers/redis.py, tests/test_db_containers.py, tests/test_docker_compose.py, tests/test_new_docker_api.py
=> Enable flake8 conformance test during CI.

testcontainers/core/container.py, tests/test_new_docker_api.py
=> Use localhost rather than 0.0.0.0 (fixes #38).

setup.cfg, setup.py
=> Add bumpversion config & release 2.6.0.

requirements.in, requirements/3.5.txt, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, setup.py, testcontainers/redis.py, tests/test_redis.py
Redis container was not working properly because it can take time to start, it should be ok now.
Let me know if I need to add/change anything else (not sure about what to do with pip-compile changes in requirements/<version>.txt).
=> update redis container and add test

testcontainers/core/container.py, testcontainers/core/docker_client.py, testcontainers/core/utils.py, tests/test_docker_compose.py, tests/test_new_docker_api.py
Changes:
- Use docker host address and mapped port if possible
- TC_HOST env to set docker host
Fix to #81, #74, #43
=> Added docker host detection and support for setting container host explicitly with env variable 

setup.py
Closes #94 
Signed-off-by: Daniel Middlecote <dlmiddlecote@gmail.com>
=> Update python_requires to have minimum of 3.5

requirements.in, requirements/3.5.txt, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt
See [here](https://community.codecov.io/t/http-400-while-uploading-to-s3-with-python-codecov-from-travis/1428/17) and https://github.com/codecov/codecov-python/issues/251 for details.
=> Update codecov to fix build.

README.rst, docs/database.rst, requirements.in, requirements/3.5.txt, requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, setup.py, testcontainers/neo4j.py, tests/test_db_containers.py
Let me know if you'd like anything else for this.
=> added Neo4j container

testcontainers/selenium.py, tests/test_selenium.py
@tillahoffmann 
As discussed in the issue #122 , here's my fix.
I've also added a test.
=> fixes #122

setup.py
=> Bump from 3.1.0 to 3.2.0.

.github/workflows/main.yml, Dockerfile, Dockerfile.diagnostics, diagnostics.py
This PR adds a script that reports testcontainers metadata and ip information.
=> Add diagnostics for tests.

testcontainers/core/generic.py
Fix dependency regression (fixes #194).
=> Fix dependency regression (fixes #194).

.gitignore, testcontainers/compose.py
Currently in this area of the code, so I took a stab at getting some docstrings in.
=> #165 Update DockerCompose docstrings

testcontainers/core/waiting_utils.py
=> Consider ConnectionError a transient exception (fixes #193).

requirements/3.6.txt, requirements/3.7.txt, requirements/3.8.txt, requirements/3.9.txt, setup.py
=> Update docker version.

.github/PULL_REQUEST_TEMPLATE/new_container.md
What it says on the tin. Thoughts on this, @yakimka?
=> Add PR template for adding new containers.

.github/workflows/main.yml, .github/workflows/pypi-release.yml
Cf https://github.com/actions/runner-images/issues/6002.
=> Run tests on `ubuntu-latest`.

testcontainers/google/pubsub.py
emulators tags is light compared to latest
=> Update cloud-sdk image

mysql/tests/test_mysql.py
Prematurely pushed 96cf752 with a broken test.
=> Fix mysql environment variable test.

elasticsearch/testcontainers/elasticsearch/__init__.py
=> FIX: Added URLError to exceptions to wait for in elasticsearch

neo4j/testcontainers/neo4j/__init__.py
That's what it looks like currently
And that's with the fix applied
=> Fix doctest layout for Neo4j

.github/settings.yml
Trying to fix the settings sync process
https://probot.github.io/apps/settings/
=> chore(settings): fix the perceived issues with settings

modules/arangodb/README.rst, modules/azurite/README.rst, modules/clickhouse/README.rst, modules/elasticsearch/README.rst, modules/google/README.rst, modules/k3s/README.rst, modules/kafka/README.rst, modules/keycloak/README.rst, modules/localstack/README.rst, modules/minio/README.rst, modules/mongodb/README.rst, modules/mssql/README.rst, modules/mysql/README.rst, modules/neo4j/README.rst, modules/nginx/README.rst, modules/opensearch/README.rst, modules/oracle/README.rst, modules/postgres/README.rst, modules/rabbitmq/README.rst, modules/redis/README.rst, modules/selenium/README.rst
It may be useful for Google SEO to index the pages
**Before:**
**After:**
=> docs: Sphinx - Add title to each doc page 

modules/rabbitmq/testcontainers/rabbitmq/__init__.py
Add pika AMQPConnectionError to transient errors
fixes #348
=> fix: rabbitmq readiness probe

poetry.lock, pyproject.toml
=> fix(cassandra): make cassandra dependency optional/test-only

core/testcontainers/core/docker_client.py
=> fix(core): env vars not being respected due to constructor call

core/testcontainers/core/container.py
=> fix(core): #486 for colima delay for port avail for connect

index.rst, modules/memcached/README.rst, modules/memcached/setup.py, modules/memcached/testcontainers/memcached/__init__.py, modules/memcached/tests/test_memcached.py, poetry.lock, pyproject.toml
Adding [Memcached](https://memcached.org/) container.
You have implemented a new container and would like to contribute it? Great! Here are the necessary steps.
=> fix: Add memcached container

core/testcontainers/core/config.py, core/testcontainers/core/docker_client.py
=> fix: move TESTCONTAINERS_HOST_OVERRIDE to config.py

modules/mailpit/testcontainers/mailpit/__init__.py
Minimal change to expose some helper methods on the `MailpitContainer`
=> fix(modules): Mailpit container base API URL helper method

modules/mysql/testcontainers/mysql/__init__.py
=> fix: mysql typo

.github/workflows/ci-core.yml, core/testcontainers/compose/compose.py, core/testcontainers/core/container.py, pyproject.toml
maybe don't write your software in python
=> fix(core): make sure context manager exits
